# Generated by Django 4.0.2 on 2022-10-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.CharField(max_length=50)),
                ('jobid', models.CharField(max_length=50)),
                ('applydate', models.CharField(max_length=50)),
                ('cname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HrReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('companyname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100)),
                ('jobdiscription', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=100)),
                ('technology', models.CharField(max_length=100)),
                ('postdate', models.CharField(max_length=100)),
                ('duedate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('technology', models.CharField(max_length=50)),
                ('candidatetype', models.CharField(max_length=50)),
                ('higereducation', models.CharField(max_length=50)),
                ('Passingyear', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('job_city', models.CharField(max_length=50)),
                ('Address', models.CharField(default=' ', max_length=50)),
                ('linkedin', models.CharField(default=' ', max_length=50)),
                ('Objective', models.CharField(default=' ', max_length=50)),
                ('Workexperience', models.CharField(default=' ', max_length=500)),
                ('ITSKILLS', models.CharField(default=' ', max_length=500)),
                ('PROJECTS', models.CharField(default=' ', max_length=500)),
                ('TRAININGS', models.CharField(default=' ', max_length=500)),
                ('HOBBIESINTEREST', models.CharField(default=' ', max_length=500)),
                ('DECLARATION', models.CharField(default=' ', max_length=500)),
                ('Date', models.CharField(default=' ', max_length=50)),
                ('sname', models.CharField(default=' ', max_length=50)),
                ('percentage', models.CharField(default=' ', max_length=500)),
                ('branch', models.CharField(default=' ', max_length=50)),
                ('Passingyear', models.CharField(default=' ', max_length=50)),
                ('course', models.CharField(default=' ', max_length=50)),
                ('univercity', models.CharField(default=' ', max_length=50)),
                ('dpercentage', models.CharField(default=' ', max_length=500)),
                ('dbranch', models.CharField(default=' ', max_length=50)),
                ('dPassingyear', models.CharField(default=' ', max_length=50)),
                ('dcourse', models.CharField(default=' ', max_length=50)),
                ('dunivercity', models.CharField(default=' ', max_length=50)),
                ('gpercentage', models.CharField(default=' ', max_length=500)),
                ('gbranch', models.CharField(default=' ', max_length=50)),
                ('gPassingyear', models.CharField(default=' ', max_length=50)),
                ('gcourse', models.CharField(default=' ', max_length=50)),
                ('gunivercity', models.CharField(default=' ', max_length=50)),
                ('pgpercentage', models.CharField(default=' ', max_length=500)),
                ('pgbranch', models.CharField(default=' ', max_length=50)),
                ('pgPassingyear', models.CharField(default=' ', max_length=50)),
                ('pgcourse', models.CharField(default=' ', max_length=50)),
                ('pgunivercity', models.CharField(default=' ', max_length=50)),
            ],
        ),
    ]
